### ISSUE TITLE
Move DynamoDB table creation to CloudFormation

### ISSUE THREAD

**Issue by p-zalejko** [p-zalejko/invoice#14]
example:
```
rDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES


```
